### ISSUE TITLE
Is it possible to add a new recipe for sagemaker-tensorflow-extensions 

### ISSUE THREAD

**Issue by gilinachum** [conda-forge/sagemaker-tensorflow-container-feedstock#29]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by rluria14** [comment]
@gilinachum yes it is possible. please feel free to open up a PR on staged-recipes
